# Generated by Django 2.0.6 on 2018-09-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportbook', '0003_mlbgame_start_time'),
        ('betslip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StraightBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now=True)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'lose'), (2, 'win')], default=0)),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sportbook.MlbOdds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
