# Generated by Django 2.0.6 on 2018-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbodds',
            name='type',
            field=models.CharField(choices=[('h_sprd', 'Home Spread'), ('a_sprd', 'Away Spread'), ('h_line', 'Home Line'), ('a_line', 'Away Line'), ('over', 'Over'), ('under', 'Under')], max_length=2),
        ),
    ]
