# Generated by Django 2.0.6 on 2018-09-22 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportbook', '0002_auto_20180920_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgame',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
